---
- name: Resolve .bashrc path
  block:
    - name: Set path to .bashrc
      set_fact:
        bashrc_path: "{{ ansible_env.HOME }}/.bashrc"
      when: bashrc_path is undefined

    - name: Check .bashrc file exists
      stat:
        path: "{{ bashrc_path }}"
      register: bashrc_path_stat

    - name: Resolve .bashrc symlink
      set_fact:
        bashrc_path: "{{ bashrc_path_stat.stat.lnk_source }}"
      when: bashrc_path_stat.stat.exists and bashrc_path_stat.stat.islnk

- name: Load nodenv in .bashrc
  block:
    - name: Check whether nodenvrc is loaded in the .bashrc file
      command: "grep -Fq 'source $HOME/.nodenvrc' {{ bashrc_path }}"
      register: check_bashrc
      ignore_errors: yes
      changed_when: no
      failed_when: no

    - name: Add .nodenvrc to .bashrc
      blockinfile:
        dest: "{{ bashrc_path }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: nodenv"
        block: |
          if [ -f "$HOME/.nodenvrc" ]; then
            source "$HOME/.nodenvrc"
          fi
      when: check_bashrc.rc != 0
  when: bashrc_path_stat.stat.exists
