---
- name: Check for nodejs {{ item }}
  stat:
    path: "{{ nodenv.path }}/versions/{{ item }}"
  register: nodejs_exists

- name: Install nodejs {{ item }}
  raw: "NODENV_ROOT={{ nodenv.path }} {{ nodenv.path }}/bin/nodenv install {{ item }}"
  notify: rehash
  when: nodejs_exists.stat is defined and not nodejs_exists.stat.exists
