---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml

- name: Set apt to use https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: Install system dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: result
  retries: 3
  until: result is succeeded
  with_items: "{{ system_dependencies }}"

- include_tasks: install-nodenv.yml

- name: Install plugins
  block:
    - name: Form merged list of plugins
      set_fact:
        merged_plugins: "{{ default_plugins | union(plugins) }}"

    - name: Install plugin {{ item.name }}
      include: install-plugins.yml
      with_items: "{{ merged_plugins }}"
      when: merged_plugins | length > 0

- name: Install nodejs versions
  include: install-nodejs.yml
  with_items:
    - "{{ nodejs.versions }}"

- name: Set global nodejs version
  block:
    - name: Check global nodejs version
      raw: "NODENV_ROOT={{ nodenv.path }} {{ nodenv.path }}/bin/nodenv global"
      register: global_nodejs_version
      changed_when: False

    - name: Set global nodejs version
      raw: "NODENV_ROOT={{ nodenv.path }} {{ nodenv.path }}/bin/nodenv global {{ nodejs.default_version }}"
      when: not global_nodejs_version.stdout is search(nodejs.default_version)
  when: nodejs.default_version is defined and nodejs.default_version | length > 0

- include_tasks: configure-shell.yml
  when: init_shell | bool
