---
- name: Set path to .bashrc
  set_fact:
    bashrc_path: "{{ ansible_env.HOME }}/.bashrc"
  when: bashrc_path is undefined

- name: Check .bashrc file exists
  stat:
    path: "{{ bashrc_path }}"
  register: bashrc_path_stat

- name: Resolve .bashrc symlink
  set_fact:
    bashrc_path: "{{ bashrc_path_stat.stat.lnk_source }}"
  when: bashrc_path_stat.stat.exists and bashrc_path_stat.stat.islnk

- name: Check whether nodenvrc is loaded in the .bashrc file
  command: "grep -Fq 'source $HOME/.nodenvrc' {{ bashrc_path }}"
  register: check_bashrc
  ignore_errors: yes
  changed_when: no
  failed_when: no
  when: bashrc_path_stat.stat.exists

- name: Load nodenvrc in .bashrc
  blockinfile:
    dest: "{{ bashrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: nodenv"
    block: |
      if [ -f "$HOME/.nodenvrc" ]; then
        source "$HOME/.nodenvrc"
      fi
  when: bashrc_path_stat.stat.exists and check_bashrc.rc != 0
